#ifndef SERVO_MOTOR_CONTROL_H
#define SERVO_MOTOR_CONTROL_H

#include"EM_Calc.h"
#include "PID.h"
#include "SERVO_MOTOR.h"

#define STEPMOTOR_Kp 0.7
#define STEPMOTOR_Ki 0.3
#define STEPMOTOR_Kd 0.5

PID SERVO_MOTOR_PID;

void SERVO_MOTOR_PID_INIT(){
    PID_INIT_NEWPID(&SERVO_MOTOR_PID,STEPMOTOR_Kp,STEPMOTOR_Ki,STEPMOTOR_Kd,0,PID_INCREASE_MODE);
}

float SERVO_MOTOR_CONTROL(int* EM_DATA){
    float CURRENT_INPUT;
    float ANGLE;
    CURRENT_INPUT=EM_CALC_POS_RES(EM_DATA);//滤波
    ANGLE=PID_CALC_RESULT(&SERVO_MOTOR_PID,CURRENT_INPUT);//用PID计算舵机打角
    SERVO_MOTOR_ANGLE(ANGLE);//让舵机打角
    return ANGLE;
}


#endif