#include "STEP_MOTOR_CONTROL.h"
#include "STEP_MOTOR.h"
#include "PID.h"
#include "LCD_show.h"

STEP_MOTOR MOTOR;
PID STEPMOTOR_PID;

void StepMotorControl_INIT(){
    PID_INIT_NEWPID(&STEPMOTOR_PID,STEERING_Kp,STEERING_Ki,STEERING_Kd,0,PID_INCREASE_MODE);
    STEP_MOTOR_INIT(&MOTOR, PWMA_CH2P_P62,PWMA_CH1P_P60, P6_0, P6_2);
}

int StepMotorControl(int CURRENT_SPEED,int TARGET_SPEED){
    // if(CURRENT_SPEED>0 && FLAG == OFF) FLAG = ON;
    // if (CURRENT_SPEED==0 && FLAG == ON || CURRENT_SPEED - TARGET_SPEED > ERROR_RANGE) {
    //     STEP_MOTOR_STOP();
    // }
    // else if(CURRENT_SPEED - TARGET_SPEED <ERROR_RANGE){
    //     STEP_MOTOR_FORWORD(STEP_MOTOR_MAX_DUTY);
    // }
    // else{
    //     PID_SET_TARGET(&MOTOR,TARGET_SPEED);
    //     STEP_MOTOR_FORWORD(PID_CALC_RESULT(&STEP_MOTOR_PID,CURRENT_SPEED));
    // }
    int delta;
    int max_pwm;
    max_pwm = MOTOR_MAX_PWM(CURRENT_SPEED);
    PID_SET_TARGET(&STEPMOTOR_PID,TARGET_SPEED);
    delta = PID_CALC_RESULT(&STEPMOTOR_PID,CURRENT_SPEED);
    MOTOR.CURRENT_PWM_DUTY = MOTOR.CURRENT_PWM_DUTY +delta ;
    if(MOTOR.CURRENT_PWM_DUTY > max_pwm) MOTOR.CURRENT_PWM_DUTY = max_pwm;//步进电机限幅
    if(MOTOR.CURRENT_PWM_DUTY < 0) MOTOR.CURRENT_PWM_DUTY = 0;
    STEP_MOTOR_FORWARD(&MOTOR,MOTOR.CURRENT_PWM_DUTY);
    //LCD("MOTOR_D",delta,6);
    //LCD("PWM",MOTOR.CURRENT_PWM_DUTY,7);
    
    return delta;
}