#include "STEP_MOTOR_CONTROL.h"

#define ERROR_RANGE 1
#define STEERING_Kp 0.5
#define STEERING_Ki 0.3
#define STEERING_Kd 0.07
#define STEP_MOTOR_MAX_DUTY 5000
#define MOTOR_MAX_PWM(speed) speed + 4000

STATUS_FLAG FLAG;
STEP_MOTOR STEP_MOTOR_L;
PID STEP_MOTOR_PID;

void STEP_MOTOR_PID_INIT(){
    PID_INIT_NEWPID(&STEP_MOTOR_PID,STEERING_Kp,STEERING_Ki,STEERING_Kd,0,PID_REALIZE_MODE);
    FLAG = OFF;
}

int STEP_MOTOR_CONTROL(uint16 CURRENT_SPEED,uint16 TARGET_SPEED){
    // if(CURRENT_SPEED>0 && FLAG == OFF) FLAG = ON;
    // if (CURRENT_SPEED==0 && FLAG == ON || CURRENT_SPEED - TARGET_SPEED > ERROR_RANGE) {
    //     STEP_MOTOR_STOP();
    // }
    // else if(CURRENT_SPEED - TARGET_SPEED <ERROR_RANGE){
    //     STEP_MOTOR_FORWORD(STEP_MOTOR_MAX_DUTY);
    // }
    // else{
    //     PID_SET_TARGET(&STEP_MOTOR_PID,TARGET_SPEED);
    //     STEP_MOTOR_FORWORD(PID_CALC_RESULT(&STEP_MOTOR_PID,CURRENT_SPEED));
    // }
    int delta;
    int max_pwm;
    max_pwm = MOTOR_MAX_PWM(CURRENT_SPEED);
    PID_SET_TARGET(&STEP_MOTOR_PID,TARGET_SPEED);
    delta = PID_CALC_RESULT(&STEP_MOTOR_PID,CURRENT_SPEED);
    STEP_MOTOR_L.CURRENT_PWM_DUTY = STEP_MOTOR_L.CURRENT_PWM_DUTY +delta ;
    if(STEP_MOTOR_L.CURRENT_PWM_DUTY > max_pwm) STEP_MOTOR_L.CURRENT_PWM_DUTY = max_pwm;
    if(STEP_MOTOR_L.CURRENT_PWM_DUTY < 0) STEP_MOTOR_L.CURRENT_PWM_DUTY = 0;
    STEP_MOTOR_FORWORD(delta);
    LCD_display("V",CURRENT_SPEED,1);
    LCD_display("delta",delta,2);
    LCD_display("PWM",STEP_MOTOR_L.CURRENT_PWM_DUTY,0);
    
    return delta;
}