#include "STEP_MOTOR_CONTROL.h"
#include "STEP_MOTOR.h"
#include "PID.h"
#include "LCD_show.h"

STEP_MOTOR STEP_MOTOR_L;
PID MySTEPMOTOR_PID;

void MyStepMotorControl_INIT(){
    PID_INIT_NEWPID(&MySTEPMOTOR_PID,STEERING_Kp,STEERING_Ki,STEERING_Kd,0,PID_REALIZE_MODE);
    STEP_MOTOR_INIT(&STEP_MOTOR_L, PWMA_CH2P_P62,PWMA_CH1P_P60, P6_0, P6_2);
}

int MyStepMotorControl_TASK(int CURRENT_SPEED,int TARGET_SPEED){
    // if(CURRENT_SPEED>0 && FLAG == OFF) FLAG = ON;
    // if (CURRENT_SPEED==0 && FLAG == ON || CURRENT_SPEED - TARGET_SPEED > ERROR_RANGE) {
    //     STEP_MOTOR_STOP();
    // }
    // else if(CURRENT_SPEED - TARGET_SPEED <ERROR_RANGE){
    //     STEP_MOTOR_FORWORD(STEP_MOTOR_MAX_DUTY);
    // }
    // else{
    //     PID_SET_TARGET(&STEP_MOTOR_PID,TARGET_SPEED);
    //     STEP_MOTOR_FORWORD(PID_CALC_RESULT(&STEP_MOTOR_PID,CURRENT_SPEED));
    // }
    int delta;
    int max_pwm;
    max_pwm = MOTOR_MAX_PWM(CURRENT_SPEED);
    PID_SET_TARGET(&MySTEPMOTOR_PID,TARGET_SPEED);
    delta = PID_CALC_RESULT(&MySTEPMOTOR_PID,CURRENT_SPEED);
    STEP_MOTOR_L.CURRENT_PWM_DUTY = STEP_MOTOR_L.CURRENT_PWM_DUTY +delta ;
    if(STEP_MOTOR_L.CURRENT_PWM_DUTY > max_pwm) STEP_MOTOR_L.CURRENT_PWM_DUTY = max_pwm;
    if(STEP_MOTOR_L.CURRENT_PWM_DUTY < 0) STEP_MOTOR_L.CURRENT_PWM_DUTY = 0;
    STEP_MOTOR_FORWARD(delta);
    LCD_display("V",CURRENT_SPEED,5);
    LCD_display("delta",delta,6);
    LCD_display("PWM",STEP_MOTOR_L.CURRENT_PWM_DUTY,7);
    
    return delta;
}