#ifndef STEP_MOTOR_H
#define STEP_MOTOR_H
#include "zf_pwm.h"
#include "zf_gpio.h"

typedef enum {
    STEP_MOTOR_P60 = PWMA_CH1P_P60,
    STEP_MOTOR_P62 = PWMA_CH2P_P62,
    STEP_MOTOR_P64 = PWMA_CH3P_P64,
    STEP_MOTOR_P66 = PWMA_CH4P_P66
} STEP_MOTOR_CHANNEL;

struct STEP_MOTOR_STRUCT {
    STEP_MOTOR_CHANNEL ALI;
    STEP_MOTOR_CHANNEL BLI;
    int CURRENT_PWM_DUTY;
};

typedef struct STEP_MOTOR_STRUCT STEP_MOTOR;

void STEP_MOTOR_INIT(STEP_MOTOR* MOTOR,STEP_MOTOR_CHANNEL ALI,STEP_MOTOR_CHANNEL BLI,PIN_enum GPIO_Pin_ALI,PIN_enum GPIO_PIN_BLI);

void STEP_MOTOR_FORWARD(STEP_MOTOR* MOTOR,int Duty);

void STEP_MOTOR_STOP(STEP_MOTOR* MOTOR);

void STEP_MOTOR_BACK(STEP_MOTOR* MOTOR,int Duty);

uint32 STEP_MOTOR_GET_DUTY(STEP_MOTOR* MOTOR);

#endif